[COURSE HEADER]
VERSION = 2
UNITS = ENGLISH
DESCRIPTION = POWER MAX 6 MIN MRC
FILE NAME = POWER MAX 6 MIN.MRC
MINUTES  PERCENT
[END COURSE HEADER]

[COURSE DATA]
0.0	80
6.0	150
6.0	80
10.0	80
[END COURSE DATA]
